# Generated by Django 4.2.7 on 2025-06-16 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, max_length=500)),
                ('language', models.CharField(max_length=10)),
                ('cultural_origin', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('wisdom', 'Wisdom Tales'), ('heroic', 'Heroic Tales'), ('origin', 'Origin Stories'), ('romance', 'Romance'), ('humor', 'Humor'), ('moral', 'Moral Stories'), ('adventure', 'Adventure')], max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('is_published', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stories',
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_session', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='stories.story')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'story_ratings',
            },
        ),
        migrations.CreateModel(
            name='StoryInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_session', models.CharField(blank=True, max_length=100, null=True)),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('like', 'Like'), ('share', 'Share'), ('bookmark', 'Bookmark'), ('complete', 'Complete Reading')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reading_time', models.IntegerField(blank=True, null=True)),
                ('completion_percentage', models.FloatField(blank=True, null=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='stories.story')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'story_interactions',
            },
        ),
        migrations.CreateModel(
            name='StoryCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stories', models.ManyToManyField(related_name='collections', to='stories.story')),
            ],
            options={
                'db_table': 'story_collections',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['language', 'category'], name='stories_languag_7fab06_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['difficulty', 'is_published'], name='stories_difficu_a6060a_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['-views'], name='stories_views_011a65_idx'),
        ),
        migrations.AddIndex(
            model_name='storyrating',
            index=models.Index(fields=['story', 'rating'], name='story_ratin_story_i_40d76a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storyrating',
            unique_together={('user', 'story')},
        ),
        migrations.AddIndex(
            model_name='storyinteraction',
            index=models.Index(fields=['story', 'interaction_type'], name='story_inter_story_i_6a0162_idx'),
        ),
        migrations.AddIndex(
            model_name='storyinteraction',
            index=models.Index(fields=['user', '-timestamp'], name='story_inter_user_id_20fa66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storyinteraction',
            unique_together={('user', 'story', 'interaction_type')},
        ),
    ]
