# Generated by Django 4.2.7 on 2025-06-16 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_session', models.CharField(blank=True, max_length=100, null=True)),
                ('source_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('source_language', models.CharField(max_length=10)),
                ('target_language', models.CharField(max_length=10)),
                ('model_used', models.CharField(default='nllb-200', max_length=100)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('user_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'translations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranslationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('correction', 'Correction'), ('rating', 'Rating'), ('report', 'Report Issue'), ('suggestion', 'Suggestion')], max_length=20)),
                ('feedback_text', models.TextField()),
                ('suggested_translation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='translations.translation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'translation_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text_hash', models.CharField(max_length=64, unique=True)),
                ('source_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('source_language', models.CharField(max_length=10)),
                ('target_language', models.CharField(max_length=10)),
                ('hit_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'translation_cache',
                'indexes': [models.Index(fields=['source_language', 'target_language'], name='translation_source__d396d2_idx'), models.Index(fields=['last_accessed'], name='translation_last_ac_d1eeb6_idx')],
            },
        ),
        migrations.CreateModel(
            name='LanguagePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_language', models.CharField(max_length=10)),
                ('target_language', models.CharField(max_length=10)),
                ('total_translations', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('average_processing_time', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('model_name', models.CharField(default='nllb-200', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'language_pairs',
                'unique_together': {('source_language', 'target_language')},
            },
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['user', '-created_at'], name='translation_user_id_15b5b2_idx'),
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['source_language', 'target_language'], name='translation_source__8f4214_idx'),
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['guest_session', '-created_at'], name='translation_guest_s_dc0da9_idx'),
        ),
    ]
