# Generated by Django 4.2.7 on 2025-06-16 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('story', 'Story'), ('game', 'Game'), ('translation', 'Translation')], max_length=20)),
                ('content_id', models.IntegerField()),
                ('content_title', models.CharField(max_length=200)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('completions', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('total_ratings', models.IntegerField(default=0)),
                ('bounce_rate', models.FloatField(default=0.0)),
                ('average_engagement_time', models.FloatField(default=0.0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'content_performance',
                'ordering': ['-date', 'content_type'],
            },
        ),
        migrations.CreateModel(
            name='FeatureUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=50)),
                ('feature_type', models.CharField(choices=[('translation', 'Translation'), ('stories', 'Stories'), ('games', 'Games'), ('tts', 'Text-to-Speech'), ('profile', 'User Profile'), ('settings', 'Settings')], max_length=20)),
                ('total_uses', models.IntegerField(default=0)),
                ('unique_users', models.IntegerField(default=0)),
                ('average_session_time', models.FloatField(default=0.0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('error_rate', models.FloatField(default=0.0)),
                ('average_response_time', models.FloatField(default=0.0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'feature_usage',
                'ordering': ['-date', 'feature_name'],
            },
        ),
        migrations.CreateModel(
            name='LanguageUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('translation_requests', models.IntegerField(default=0)),
                ('story_views', models.IntegerField(default=0)),
                ('game_plays', models.IntegerField(default=0)),
                ('tts_requests', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('unique_users', models.IntegerField(default=0)),
                ('guest_users', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'language_usage',
                'ordering': ['-date', 'language_code'],
            },
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_users', models.IntegerField(default=0)),
                ('active_users_daily', models.IntegerField(default=0)),
                ('active_users_weekly', models.IntegerField(default=0)),
                ('active_users_monthly', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('total_translations', models.IntegerField(default=0)),
                ('total_stories', models.IntegerField(default=0)),
                ('total_games_played', models.IntegerField(default=0)),
                ('average_response_time', models.FloatField(default=0.0)),
                ('error_rate', models.FloatField(default=0.0)),
                ('uptime_percentage', models.FloatField(default=100.0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'system_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_session', models.CharField(blank=True, max_length=100, null=True)),
                ('session_start', models.DateTimeField(auto_now_add=True)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('session_duration', models.IntegerField(blank=True, null=True)),
                ('pages_visited', models.JSONField(default=list)),
                ('features_used', models.JSONField(default=list)),
                ('actions_performed', models.IntegerField(default=0)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'user_engagement',
                'ordering': ['-session_start'],
            },
        ),
        migrations.CreateModel(
            name='UserRetention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_1_return', models.BooleanField(default=False)),
                ('day_7_return', models.BooleanField(default=False)),
                ('day_30_return', models.BooleanField(default=False)),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_time_spent', models.IntegerField(default=0)),
                ('features_used_count', models.IntegerField(default=0)),
                ('high_engagement_sessions', models.IntegerField(default=0)),
                ('content_created', models.IntegerField(default=0)),
                ('social_interactions', models.IntegerField(default=0)),
                ('cohort_week', models.DateField()),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_retention',
                'ordering': ['-cohort_week', 'user'],
            },
        ),
    ]
