# Generated by Django 4.2.7 on 2025-06-16 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userretention',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userengagement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='languageusage',
            unique_together={('language_code', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='featureusage',
            unique_together={('feature_name', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='contentperformance',
            unique_together={('content_type', 'content_id', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='userretention',
            unique_together={('user', 'cohort_week')},
        ),
        migrations.AddIndex(
            model_name='userengagement',
            index=models.Index(fields=['user', '-session_start'], name='user_engage_user_id_2873c1_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagement',
            index=models.Index(fields=['session_start'], name='user_engage_session_50da4b_idx'),
        ),
    ]
