# Generated by Django 4.2.7 on 2025-06-16 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('model_type', models.CharField(choices=[('translation', 'Translation'), ('tts', 'Text-to-Speech'), ('asr', 'Automatic Speech Recognition'), ('embedding', 'Text Embedding')], max_length=20)),
                ('model_path', models.CharField(max_length=500)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('max_input_length', models.IntegerField(default=512)),
                ('supported_languages', models.JSONField(default=list)),
                ('average_processing_time', models.FloatField(default=0.0)),
                ('total_requests', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_models',
                'ordering': ['model_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('output_text', models.TextField(blank=True)),
                ('source_language', models.CharField(blank=True, max_length=10)),
                ('target_language', models.CharField(blank=True, max_length=10)),
                ('processing_time', models.FloatField()),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='ai_models.aimodel')),
            ],
            options={
                'db_table': 'model_requests',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model', '-timestamp'], name='model_reque_model_i_b43439_idx'), models.Index(fields=['success', '-timestamp'], name='model_reque_success_1c7c2e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModelCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_hash', models.CharField(max_length=64, unique=True)),
                ('input_text', models.TextField()),
                ('output_text', models.TextField()),
                ('hit_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cache', to='ai_models.aimodel')),
            ],
            options={
                'db_table': 'model_cache',
                'indexes': [models.Index(fields=['model', 'input_hash'], name='model_cache_model_i_b275c4_idx'), models.Index(fields=['expires_at'], name='model_cache_expires_aef19f_idx')],
            },
        ),
        migrations.CreateModel(
            name='LanguageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('language_name', models.CharField(max_length=100)),
                ('is_supported', models.BooleanField(default=True)),
                ('quality_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asr_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asr_languages', to='ai_models.aimodel')),
                ('translation_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_languages', to='ai_models.aimodel')),
                ('tts_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tts_languages', to='ai_models.aimodel')),
            ],
            options={
                'db_table': 'language_models',
                'unique_together': {('language_code',)},
            },
        ),
    ]
